# Generated by Django 2.1.5 on 2020-10-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(null=True)),
                ('text', models.TextField(null=True)),
                ('rasmer', models.CharField(max_length=150)),
                ('image1', models.ImageField(blank=True, upload_to='user_images')),
                ('image2', models.ImageField(blank=True, upload_to='user_images')),
                ('image3', models.ImageField(blank=True, upload_to='user_images')),
                ('image4', models.ImageField(blank=True, upload_to='user_images')),
            ],
        ),
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(null=True)),
                ('text', models.TextField(null=True)),
                ('image1', models.ImageField(blank=True, upload_to='user_images')),
                ('image2', models.ImageField(blank=True, upload_to='user_images')),
                ('image3', models.ImageField(blank=True, upload_to='user_images')),
                ('image4', models.ImageField(blank=True, upload_to='user_images')),
            ],
        ),
        migrations.CreateModel(
            name='top',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
